db:
  image: mongo
# volumes:
#    - ./data/runtime/db:/data/db
#    - ./data/dump:/dump
  command: mongod --smallfiles

rocketchat:
  image: rocketchat/rocket.chat
  environment:
    - VIRTUAL_HOST=chat.docker.dev
    - VIRTUAL_PORT=3000
    - MONGO_URL=mongodb://db:27017/rocketchat
    - ROOT_URL=http://yourhost:8818
  links:
    - db:db
  ports:
    - 8818:3000
